jobs:
  include:
    - stage: test
      language: node_js
      cache: npm
      node_js:
        - 12
        - 10
      install:
        - npm ci
      script:
        - npm run lint
        - npm run test:coverage
      after_script:
        - npx codeclimate-test-reporter < coverage/lcov.info
    - stage: release
      language: node_js
      node_js:
        - 10
      install:
        - npm i --save-dev --save-exact @semantic-release/git @semantic-release/changelog
      script:
        - npx semantic-release
stages:
  - test
  - name: release
    if: branch = master AND type != pull_request
