name: Release

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run tests and linting
      run: |
        npm ci
        npm run lint
        npm run test:coverage
        npx codeclimate-test-reporter < coverage/lcov.info
      env:
        CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        CI: true

    - name: Create release using semantic-release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CI: true
